import { ArrowLeft } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { AssetForm } from '../../components/assets/AssetForm';
import { Button, Card, ErrorState, PageHeader, Skeleton } from '../../components/common';
import { useAuth } from '../../hooks/useAuth';
import { createAsset, getAsset, updateAsset } from '../../services/assetService';
import { uploadFile } from '../../services/storageService';
import { createAssetCode, getErrorMessage } from '../../utils/helpers';

export default function AssetFormPage() { const { assetId } = useParams(); const editing = Boolean(assetId); const { user } = useAuth(); const navigate = useNavigate(); const [asset, setAsset] = useState(null); const [loadingAsset, setLoadingAsset] = useState(editing); const [loading, setLoading] = useState(false); const [missing, setMissing] = useState(false); useEffect(() => { if (!editing) return; getAsset(assetId).then((data) => { if (data) setAsset(data); else setMissing(true); }).catch(() => setMissing(true)).finally(() => setLoadingAsset(false)); }, [assetId, editing]); const submit = async (values, imageFile) => { setLoading(true); try { let image = values.image || ''; if (imageFile) image = await uploadFile(imageFile, `users/${user.uid}/assets/${Date.now()}-${imageFile.name}`); const payload = { ...values, image, assetCode: values.assetCode || createAssetCode() }; if (editing) { await updateAsset(assetId, payload); toast.success('Asset updated.'); navigate(`/assets/${assetId}`); } else { const id = await createAsset(payload, user.uid); toast.success('Asset created and QR code assigned.'); navigate(`/assets/${id}`); } } catch (error) { toast.error(getErrorMessage(error)); } finally { setLoading(false); } }; if (loadingAsset) return <div className="space-y-6"><Skeleton className="h-20 w-1/2" /><Skeleton className="h-[520px]" /></div>; if (missing) return <ErrorState title="Asset not found" description="It may have been removed or is no longer available." action={<Link to="/assets"><Button>Back to assets</Button></Link>} />; return <div className="mx-auto max-w-4xl space-y-7 animate-soft-in"><PageHeader eyebrow={editing ? 'Edit asset' : 'New asset'} title={editing ? `Update ${asset.assetName}` : 'Put an asset on record'} description="A few useful details now create a much clearer maintenance history later." actions={<Link to={editing ? `/assets/${assetId}` : '/assets'}><Button variant="secondary"><ArrowLeft size={16} />Cancel</Button></Link>} /><Card className="p-5 sm:p-7"><AssetForm asset={asset || { assetCode: createAssetCode() }} onSubmit={submit} loading={loading} /></Card></div>; }
