import { Bell, ChevronDown, Menu, Moon, Search, Sun } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { useTheme } from '../../hooks/useTheme';

const initials = (name) => name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'U';

export function Topbar({ onMenu }) { const { user, profile, logout } = useAuth(); const { theme, toggleTheme } = useTheme(); const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const navigate = useNavigate(); const submitSearch = (event) => { event.preventDefault(); navigate(`/assets?search=${encodeURIComponent(search)}`); };
  return <header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-line bg-canvas/85 px-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/85 sm:px-6 lg:px-8"><button aria-label="Open menu" onClick={onMenu} className="rounded-lg p-2 text-muted hover:bg-slate-100 dark:hover:bg-slate-800 lg:hidden"><Menu size={20} /></button><form onSubmit={submitSearch} className="relative hidden max-w-md flex-1 md:block"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search assets…" className="h-10 w-full rounded-xl border border-line bg-white pl-10 pr-3 text-sm outline-none transition focus:border-brand-500 focus:ring-4 focus:ring-brand-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:focus:ring-brand-950" /></form><div className="ml-auto flex items-center gap-1.5"><button aria-label="Toggle theme" onClick={toggleTheme} className="rounded-lg p-2.5 text-muted hover:bg-slate-100 hover:text-ink dark:hover:bg-slate-800 dark:hover:text-white">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button aria-label="Notifications" className="relative rounded-lg p-2.5 text-muted hover:bg-slate-100 hover:text-ink dark:hover:bg-slate-800 dark:hover:text-white"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-brand-600" /></button><div className="relative"><button onClick={() => setOpen((value) => !value)} className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800"><span className="grid h-8 w-8 place-items-center overflow-hidden rounded-lg bg-brand-100 text-xs font-bold text-brand-700 dark:bg-brand-950 dark:text-brand-300">{profile?.photoURL ? <img src={profile.photoURL} alt="" className="h-full w-full object-cover" /> : initials(profile?.name || user?.displayName)}</span><span className="hidden text-left sm:block"><span className="block max-w-28 truncate text-sm font-semibold text-ink dark:text-white">{profile?.name || user?.displayName || 'Account'}</span><span className="block text-xs text-muted">{profile?.role || 'Member'}</span></span><ChevronDown size={15} className="hidden text-muted sm:block" /></button>{open && <div className="absolute right-0 mt-2 w-48 rounded-xl border border-line bg-white p-1.5 shadow-float dark:border-slate-700 dark:bg-slate-900"><Link onClick={() => setOpen(false)} to="/profile" className="block rounded-lg px-3 py-2 text-sm text-ink hover:bg-slate-50 dark:text-slate-100 dark:hover:bg-slate-800">Profile</Link><Link onClick={() => setOpen(false)} to="/settings" className="block rounded-lg px-3 py-2 text-sm text-ink hover:bg-slate-50 dark:text-slate-100 dark:hover:bg-slate-800">Settings</Link><button onClick={logout} className="block w-full rounded-lg px-3 py-2 text-left text-sm text-danger hover:bg-red-50 dark:hover:bg-red-950/30">Log out</button></div>}</div></div></header>; }
